packages:
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

allowedDeprecatedVersions:
  'glob': '10.5.0'

publicHoistPattern:
  - '@types/*'
  - typescript

updateConfig:
  ignoreDependencies:
    - typescript
    - vite

catalog:
  typescript: '^6.0.0'
  vite: '^7.0.0'
